version: "3.4"

services:
  web:
    image: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: nginx
    networks:
      - nodenetwork
    depends_on:
      - node
  node:
    image: node:15
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: node
    networks:
      - nodenetwork
    volumes:
      - ./node:/usr/src/app

    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    networks:
      - nodenetwork
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
      MYSQL_USER: guest
      MYSQL_PASSWORD: guest
    volumes:
      - ./mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 3

networks:
  nodenetwork:
    driver: bridge
